#' @title Get Report Download URL
#' @description get_download_url request the download URL related to the report id generated by get_report_id().
#' @param bing_auth auth object generated with authenticate()
#' @param report_id report id generated by get_report_id()
#' @importFrom XML xmlToList
#' @importFrom RCurl curlPerform basicTextGatherer
#' @return url character string
get_download_url <- function(bing_auth, report_id) {
  url <-
    "https://reporting.api.bingads.microsoft.com/Api/Advertiser/Reporting/v13/ReportingService.svc"
  soap_action <- "PollGenerateReport"
  report <- "PollGenerateReportRequest"
  header <-
    paste(readLines(
      paste0(
        system.file(package = "RBingAds"),
        "/xml/reporting.header.authtokens.xml"
      )
    ), collapse = "")
  body_xml <-
    paste(readLines(
      paste0(
        system.file(package = "RBingAds"),
        "/xml/reporting.pollGenerateReportRequest.reportid.xml"
      )
    ), collapse = "")
  body_xml <- sprintf(body_xml, report_id)
  body <- sprintf(
    header,
    soap_action,
    bing_auth$credentials$c_id,
    bing_auth$access$access_token,
    bing_auth$credentials$auth_developer_token,
    body_xml
  )
  header_fields =  c(
    Accept = "text/xml",
    Accept = "multipart/*",
    'Content-Type' = "text/xml;charset=utf-8",
    SOAPAction = soap_action
  )
  h = basicTextGatherer()
  curlPerform(
    url = url,
    httpheader = header_fields,
    postfields = body,
    writefunction = h$update
  )
  downloadUrl <-
    xmlToList(h$value())$Body$PollGenerateReportResponse$ReportRequestStatus$ReportDownloadUrl
  return(downloadUrl)
}
